import{a as v,S as E,i as n}from"./assets/vendor-hdXJlIEV.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&c(f)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const y=15,A="52465106-83256c19c806c121527b257ca",q="https://pixabay.com/api/";async function g(r,o){const e={key:A,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:y};return(await v.get(q,{params:e})).data}const p=document.querySelector(".gallery"),d=document.querySelector(".btn-more"),b=document.querySelector(".box-loader");let P=new E(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){const o=r.map(e=>`
      <li class="photo-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),P.refresh()}function x(){p.innerHTML=""}function S(){b.classList.remove("is-hidden")}function u(){b.classList.add("is-hidden")}function w(){d.classList.remove("is-hidden")}function l(){d.classList.add("is-hidden")}const h=document.querySelector(".form"),B=h?.querySelector('input[name="search-text"]');let m="",a=1,i=0;d&&d.addEventListener("click",$);h&&h.addEventListener("submit",M);l();u();async function M(r){r.preventDefault();const o=B?.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a word"});return}m=o,a=1,i=0,x(),l();try{S();const e=await g(m,a);i=e.totalHits??0;const c=Array.isArray(e.hits)?e.hits:[];if(c.length===0){n.info({title:"No results",message:"No images found. Try again."}),u();return}L(c),n.success({title:"Success",message:`Wow, there are ${i} images!`}),a*y<i?w():(l(),n.info({title:"End",message:"Sorry, but you've reached the end of search results."}))}catch(e){console.error(e),n.error({title:"Error",message:"Something went wrong. Please try again."})}finally{u()}}async function $(){a+=1;try{S();const r=await g(m,a),o=Array.isArray(r.hits)?r.hits:[];if(i=r.totalHits??i,o.length===0){l(),n.info({title:"End",message:"Sorry, but you've reached the end of search results."});return}L(o),F(),a*y>=i?(l(),n.info({title:"End",message:"Sorry, but you've reached the end of search results."})):w()}catch(r){console.error(r),n.error({title:"Error",message:"Failed to load more images."}),a=Math.max(1,a-1)}finally{u()}}function F(){const r=p.querySelector(".photo-card");if(!r)return;const{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
